# taken from https://github.com/marketplace/actions/jsdoc-action
name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create output directory
        run: |
          mkdir -p ./out
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./types
          output_dir: ./out
          template: minami
          front_page: README.md
      - name: Funny Debug step 1
        run: |
          touch ./out/IHATEYOU.md
      - name: Funny Debug step 2
        run: |
          ls -lah ./out
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out